/* Generated by spimdisasm 1.24.2 */

/* Handwritten function */
glabel AsmGetEPC
/* 58A58 80068258 00700240 */  mfc0       $v0, $14 /* handwritten instruction */
/* 58A5C 8006825C 0800E003 */  jr         $ra
/* 58A60 80068260 00000000 */   nop
.size AsmGetEPC, . - AsmGetEPC

/* Handwritten function */
glabel exceptionHandler
/* 58A64 80068264 0B801A3C */  lui        $k0, (0x800B0000 >> 16) /* handwritten instruction */
/* 58A68 80068268 F8B45A27 */  addiu      $k0, $k0, -0x4B08 /* handwritten instruction */
/* 58A6C 8006826C 000041AF */  sw         $at, 0x0($k0) /* handwritten instruction */
/* 58A70 80068270 040042AF */  sw         $v0, 0x4($k0) /* handwritten instruction */
/* 58A74 80068274 00680140 */  mfc0       $at, $13 /* handwritten instruction */
/* 58A78 80068278 00000000 */  nop
/* 58A7C 8006827C 080041AF */  sw         $at, 0x8($k0) /* handwritten instruction */
/* 58A80 80068280 82080100 */  srl        $at, $at, 2
/* 58A84 80068284 1F002130 */  andi       $at, $at, 0x1F
/* 58A88 80068288 35002010 */  beqz       $at, .L80068360
/* 58A8C 8006828C 09002238 */   xori      $v0, $at, 0x9
/* 58A90 80068290 4F004010 */  beqz       $v0, .L800683D0
/* 58A94 80068294 08002238 */   xori      $v0, $at, 0x8
/* 58A98 80068298 42004010 */  beqz       $v0, .L800683A4
/* 58A9C 8006829C 0C0041AF */   sw        $at, 0xC($k0) /* handwritten instruction */
/* 58AA0 800682A0 00700140 */  mfc0       $at, $14 /* handwritten instruction */
/* 58AA4 800682A4 00000000 */  nop
/* 58AA8 800682A8 100041AF */  sw         $at, 0x10($k0) /* handwritten instruction */
/* 58AAC 800682AC 00400140 */  mfc0       $at, $8 /* handwritten instruction */
/* 58AB0 800682B0 00000000 */  nop
/* 58AB4 800682B4 140041AF */  sw         $at, 0x14($k0) /* handwritten instruction */
/* 58AB8 800682B8 00600140 */  mfc0       $at, $12 /* handwritten instruction */
/* 58ABC 800682BC 00000000 */  nop
/* 58AC0 800682C0 180041AF */  sw         $at, 0x18($k0) /* handwritten instruction */
/* 58AC4 800682C4 00780140 */  mfc0       $at, $15 /* handwritten instruction */
/* 58AC8 800682C8 00000000 */  nop
/* 58ACC 800682CC 1C0041AF */  sw         $at, 0x1C($k0) /* handwritten instruction */
/* 58AD0 800682D0 0000418F */  lw         $at, 0x0($k0) /* handwritten instruction */
/* 58AD4 800682D4 0400428F */  lw         $v0, 0x4($k0) /* handwritten instruction */
/* 58AD8 800682D8 200040AF */  sw         $zero, 0x20($k0) /* handwritten instruction */
/* 58ADC 800682DC 240041AF */  sw         $at, 0x24($k0) /* handwritten instruction */
/* 58AE0 800682E0 280042AF */  sw         $v0, 0x28($k0) /* handwritten instruction */
/* 58AE4 800682E4 2C0043AF */  sw         $v1, 0x2C($k0) /* handwritten instruction */
/* 58AE8 800682E8 300044AF */  sw         $a0, 0x30($k0) /* handwritten instruction */
/* 58AEC 800682EC 340045AF */  sw         $a1, 0x34($k0) /* handwritten instruction */
/* 58AF0 800682F0 380046AF */  sw         $a2, 0x38($k0) /* handwritten instruction */
/* 58AF4 800682F4 3C0047AF */  sw         $a3, 0x3C($k0) /* handwritten instruction */
/* 58AF8 800682F8 400048AF */  sw         $t0, 0x40($k0) /* handwritten instruction */
/* 58AFC 800682FC 440049AF */  sw         $t1, 0x44($k0) /* handwritten instruction */
/* 58B00 80068300 48004AAF */  sw         $t2, 0x48($k0) /* handwritten instruction */
/* 58B04 80068304 4C004BAF */  sw         $t3, 0x4C($k0) /* handwritten instruction */
/* 58B08 80068308 50004CAF */  sw         $t4, 0x50($k0) /* handwritten instruction */
/* 58B0C 8006830C 54004DAF */  sw         $t5, 0x54($k0) /* handwritten instruction */
/* 58B10 80068310 58004EAF */  sw         $t6, 0x58($k0) /* handwritten instruction */
/* 58B14 80068314 5C004FAF */  sw         $t7, 0x5C($k0) /* handwritten instruction */
/* 58B18 80068318 600050AF */  sw         $s0, 0x60($k0) /* handwritten instruction */
/* 58B1C 8006831C 640051AF */  sw         $s1, 0x64($k0) /* handwritten instruction */
/* 58B20 80068320 680052AF */  sw         $s2, 0x68($k0) /* handwritten instruction */
/* 58B24 80068324 6C0053AF */  sw         $s3, 0x6C($k0) /* handwritten instruction */
/* 58B28 80068328 700054AF */  sw         $s4, 0x70($k0) /* handwritten instruction */
/* 58B2C 8006832C 740055AF */  sw         $s5, 0x74($k0) /* handwritten instruction */
/* 58B30 80068330 780056AF */  sw         $s6, 0x78($k0) /* handwritten instruction */
/* 58B34 80068334 7C0057AF */  sw         $s7, 0x7C($k0) /* handwritten instruction */
/* 58B38 80068338 800058AF */  sw         $t8, 0x80($k0) /* handwritten instruction */
/* 58B3C 8006833C 840059AF */  sw         $t9, 0x84($k0) /* handwritten instruction */
/* 58B40 80068340 88005AAF */  sw         $k0, 0x88($k0) /* handwritten instruction */
/* 58B44 80068344 8C005BAF */  sw         $k1, 0x8C($k0) /* handwritten instruction */
/* 58B48 80068348 90005CAF */  sw         $gp, 0x90($k0) /* handwritten instruction */
/* 58B4C 8006834C 94005DAF */  sw         $sp, 0x94($k0) /* handwritten instruction */
/* 58B50 80068350 98005EAF */  sw         $fp, 0x98($k0) /* handwritten instruction */
/* 58B54 80068354 9C005FAF */  sw         $ra, 0x9C($k0) /* handwritten instruction */
/* 58B58 80068358 C05F010C */  jal        AlertNew
/* 58B5C 8006835C 00000000 */   nop
.L80068360:
/* 58B60 80068360 00000000 */  nop
/* 58B64 80068364 A000418F */  lw         $at, 0xA0($k0) /* handwritten instruction */
/* 58B68 80068368 00000000 */  nop
/* 58B6C 8006836C 01002120 */  addi       $at, $at, 0x1 /* handwritten instruction */
/* 58B70 80068370 A00041AF */  sw         $at, 0xA0($k0) /* handwritten instruction */
/* 58B74 80068374 00000000 */  nop
/* 58B78 80068378 00680140 */  mfc0       $at, $13 /* handwritten instruction */
/* 58B7C 8006837C 00000000 */  nop
/* 58B80 80068380 00FF2130 */  andi       $at, $at, 0xFF00
/* 58B84 80068384 00000000 */  nop
/* 58B88 80068388 AC0041AF */  sw         $at, 0xAC($k0) /* handwritten instruction */
/* 58B8C 8006838C 00000000 */  nop
/* 58B90 80068390 0000418F */  lw         $at, 0x0($k0) /* handwritten instruction */
/* 58B94 80068394 00000000 */  nop
/* 58B98 80068398 0400428F */  lw         $v0, 0x4($k0) /* handwritten instruction */
/* 58B9C 8006839C 00000000 */  nop
/* 58BA0 800683A0 FFA00108 */  j          oldExceptionHandler
.L800683A4:
/* 58BA4 800683A4 00000000 */   nop
/* 58BA8 800683A8 A400418F */  lw         $at, 0xA4($k0) /* handwritten instruction */
/* 58BAC 800683AC 00000000 */  nop
/* 58BB0 800683B0 01002120 */  addi       $at, $at, 0x1 /* handwritten instruction */
/* 58BB4 800683B4 A40041AF */  sw         $at, 0xA4($k0) /* handwritten instruction */
/* 58BB8 800683B8 00000000 */  nop
/* 58BBC 800683BC 0000418F */  lw         $at, 0x0($k0) /* handwritten instruction */
/* 58BC0 800683C0 00000000 */  nop
/* 58BC4 800683C4 0400428F */  lw         $v0, 0x4($k0) /* handwritten instruction */
/* 58BC8 800683C8 00000000 */  nop
/* 58BCC 800683CC FFA00108 */  j          oldExceptionHandler
.L800683D0:
/* 58BD0 800683D0 00000000 */   nop
/* 58BD4 800683D4 A800418F */  lw         $at, 0xA8($k0) /* handwritten instruction */
/* 58BD8 800683D8 00000000 */  nop
/* 58BDC 800683DC 01002120 */  addi       $at, $at, 0x1 /* handwritten instruction */
/* 58BE0 800683E0 A80041AF */  sw         $at, 0xA8($k0) /* handwritten instruction */
/* 58BE4 800683E4 00000000 */  nop
/* 58BE8 800683E8 0000418F */  lw         $at, 0x0($k0) /* handwritten instruction */
/* 58BEC 800683EC 00000000 */  nop
/* 58BF0 800683F0 0400428F */  lw         $v0, 0x4($k0) /* handwritten instruction */
/* 58BF4 800683F4 00000000 */  nop
/* 58BF8 800683F8 FFA00108 */  j          oldExceptionHandler
.size exceptionHandler, . - exceptionHandler

glabel oldExceptionHandler
/* 58BFC 800683FC 00000000 */  nop
/* 58C00 80068400 00000000 */  nop
/* 58C04 80068404 00000000 */  nop
/* 58C08 80068408 00000000 */  nop
/* 58C0C 8006840C 00000000 */  nop
/* 58C10 80068410 00000000 */  nop
/* 58C14 80068414 00000000 */  nop
/* 58C18 80068418 00000000 */  nop
/* 58C1C 8006841C 0800E003 */  jr         $ra
/* 58C20 80068420 00000000 */   nop
.size oldExceptionHandler, . - oldExceptionHandler

glabel HWBP_handler
/* 58C24 80068424 0B801A3C */ .word 0x3C1A800B
/* 58C28 80068428 F8B45A27 */ .word 0x275AB4F8
/* 58C2C 8006842C BC0042AF */ .word 0xAF4200BC
/* 58C30 80068430 00000000 */ .word 0x00000000
/* 58C34 80068434 00700240 */ .word 0x40027000
/* 58C38 80068438 00000000 */ .word 0x00000000
/* 58C3C 8006843C C00042AF */ .word 0xAF4200C0
/* 58C40 80068440 00000000 */ .word 0x00000000
/* 58C44 80068444 BC00428F */ .word 0x8F4200BC
/* 58C48 80068448 00000000 */ .word 0x00000000
/* 58C4C 8006844C 80E01A3C */ .word 0x3C1AE080
/* 58C50 80068450 00389A40 */ .word 0x409A3800
/* 58C54 80068454 00701A40 */ .word 0x401A7000
/* 58C58 80068458 00000000 */ .word 0x00000000
/* 58C5C 8006845C 08004003 */ .word 0x03400008
/* 58C60 80068460 10000042 */ .word 0x42000010 /* invalid instruction */
.size HWBP_handler, . - HWBP_handler
