/* Generated by spimdisasm 1.24.2 */

/* Handwritten function */
glabel UnlinkNTagR
/* 3B308 8004AB08 FFFFA524 */  addiu      $a1, $a1, -0x1
/* 3B30C 8004AB0C C0400500 */  sll        $t0, $a1, 3
/* 3B310 8004AB10 20208800 */  add        $a0, $a0, $t0 /* handwritten instruction */
/* 3B314 8004AB14 00008A8C */  lw         $t2, 0x0($a0)
/* 3B318 8004AB18 0000CB8C */  lw         $t3, 0x0($a2)
/* 3B31C 8004AB1C FF00083C */  lui        $t0, (0xFFFFFF >> 16)
/* 3B320 8004AB20 FFFF0835 */  ori        $t0, $t0, (0xFFFFFF & 0xFFFF)
/* 3B324 8004AB24 00FF093C */  lui        $t1, (0xFF000000 >> 16)
.L8004AB28:
/* 3B328 8004AB28 08004011 */  beqz       $t2, .L8004AB4C
/* 3B32C 8004AB2C 24504801 */   and       $t2, $t2, $t0
/* 3B330 8004AB30 0400878C */  lw         $a3, 0x4($a0)
/* 3B334 8004AB34 24586901 */  and        $t3, $t3, $t1
/* 3B338 8004AB38 25586A01 */  or         $t3, $t3, $t2
/* 3B33C 8004AB3C 000080AC */  sw         $zero, 0x0($a0)
/* 3B340 8004AB40 0000CBAC */  sw         $t3, 0x0($a2)
/* 3B344 8004AB44 2130E000 */  addu       $a2, $a3, $zero
/* 3B348 8004AB48 0000CB8C */  lw         $t3, 0x0($a2)
.L8004AB4C:
/* 3B34C 8004AB4C F8FF8A8C */  lw         $t2, -0x8($a0)
/* 3B350 8004AB50 F8FF8424 */  addiu      $a0, $a0, -0x8
/* 3B354 8004AB54 F4FFA014 */  bnez       $a1, .L8004AB28
/* 3B358 8004AB58 FFFFA524 */   addiu     $a1, $a1, -0x1
/* 3B35C 8004AB5C 25586801 */  or         $t3, $t3, $t0
/* 3B360 8004AB60 0800E003 */  jr         $ra
/* 3B364 8004AB64 0000CBAC */   sw        $t3, 0x0($a2)
.size UnlinkNTagR, . - UnlinkNTagR
